### ISSUE TITLE
Enhancement: Complete Layout Implementation - Close Template Gaps

### ISSUE THREAD

**Issue by teknologika** [teknologika/Deckbuilder#8]
## Template Gap Analysis

Based on analysis of `default.json` vs current implementation, we have **6 layouts defined in the template but not fully implemented** in the Deckbuilder code.

## Current State
- ✅ **9 layouts fully implemented** (Title Slide, Title and Content, Section Header, Two Content, Comparison, Title Only, Blank, Content with Caption, Picture with Caption)
- ✅ **4 layouts partially implemented** (Three/Four Columns - structured frontmatter exists)
- ❌ **6 layouts template-only** (need implementation)

### 1. Title and Vertical Text (index: 9)
**Template Definition:** `title_top_1`, `content_1`
**Gap:** No structured frontmatter or special handling
**Placeholder mapping:** Same as Title and Content but different visual layout

### 2. Vertical Title and Text (index: 10)  
**Template Definition:** `title_top_1`, `content_1`
**Gap:** No structured frontmatter or special handling
**Placeholder mapping:** Same as Title and Content but different visual orientation

### 3. Four Columns (index: 14)
**Template Definition:** `title_top_1`, `content_col1_1`, `content_col2_1`, `content_col3_1`, `content_col4_1`
**Gap:** Structured frontmatter exists for "Four Columns With Titles" but not "Four Columns" (content-only)
**Need:** Add structured frontmatter pattern for columns without titles

### 4. Agenda, 6 Textboxes (index: 15)
**Template Definition:** Complex agenda items with numbers and content
**Placeholders:** `number_item1_1` through `number_item6_1`, `content_item1_1` through `content_item6_1`
**Gap:** No structured frontmatter for agenda items
**Need:** Structured frontmatter for agenda/checklist layouts

### 5. Title and 6-item Lists (index: 16)
**Template Definition:** Multiple content areas with complex numbering
**Gap:** No structured frontmatter implementation
**Need:** Structured frontmatter for complex list layouts

### 6. Big Number (index: 17)
**Template Definition:** `title_top_1`, `content_1` 
**Gap:** No special handling for large number display
**Need:** Structured frontmatter for metric/statistic presentations

### 7. SWOT Analysis (index: 18)
**Template Definition:** Four content areas for Strengths, Weaknesses, Opportunities, Threats
**Placeholders:** `content_16`, `content_17`, `content_18`, `content_19`
**Gap:** No structured frontmatter for SWOT analysis
**Need:** Structured frontmatter with SWOT-specific fields

### Phase 1: Structured Frontmatter Patterns
Add structured frontmatter definitions to `structured_frontmatter.py`:

#### Four Columns (Content Only)
```yaml
---
layout: Four Columns
title: Benefits Overview  
columns:
  - content: "Fast processing with optimized algorithms"
  - content: "Enterprise-grade encryption and compliance"
  - content: "Intuitive interface with minimal learning"
  - content: "Competitive pricing with flexible plans"
---
```

#### Agenda, 6 Textboxes
```yaml
---
layout: Agenda, 6 Textboxes
title: Project Roadmap
agenda:
  - number: "1"
    content: "Requirements gathering and analysis"
  - number: "2" 
    content: "System design and architecture"
  - number: "3"
    content: "Development and implementation"
  - number: "4"
    content: "Testing and quality assurance"
  - number: "5"
    content: "Deployment and go-live"
  - number: "6"
    content: "Monitoring and optimization"
---
```

#### SWOT Analysis
```yaml
---
layout: SWOT Analysis
swot:
  strengths:
    - "Strong market position"
    - "Experienced team"
  weaknesses:
    - "Limited resources"
    - "Technology debt"
  opportunities:
    - "Market expansion"
    - "New partnerships"
  threats:
    - "Increased competition"
    - "Economic uncertainty"
---
```

#### Big Number
```yaml
---
layout: Big Number
title: Key Metric
metric:
  number: "94%"
  description: "Customer satisfaction rate increased significantly"
---
```

### Phase 2: Placeholder Mapping
Update `_generate_mapping_rules()" in structured_frontmatter.py to handle:
- Agenda item numbering and content mapping
- SWOT quadrant mapping (strengths/weaknesses/opportunities/threats)
- Column content without titles
- Big number metric formatting

### Phase 3: Validation Rules
Add validation for:
- Agenda items (1-6 items maximum)
- SWOT analysis (required quadrants)
- Column content validation
- Big number format validation

### Phase 4: Test Coverage
Add comprehensive test cases to:
- `test_presentation.md` - Frontmatter examples for all new layouts
- `test_presentation.json` - JSON examples for all new layouts
- Unit tests for structured frontmatter parsing

### Phase 5: Documentation Updates
Update layout intelligence and documentation:
- `layout_intelligence.json` - Add content patterns for new layouts
- `Getting_Started.md` - Include all layouts when feature #8 is implemented
- Template analysis tools - Recognize and validate new layouts

## Success Criteria
- ✅ All 19 template layouts have structured frontmatter support
- ✅ All layouts work with both Markdown and JSON input
- ✅ Comprehensive test coverage for all layouts
- ✅ Documentation includes complete layout reference
- ✅ Template analysis tools recognize all layouts

## Dependencies
- Should be implemented **after** CLI enhancement feature (Getting_Started.md generation)
- Requires updates to template analysis in `cli_tools.py`
- May need template validation updates

## Priority
- **Medium** - Completes the template implementation but not blocking core functionality
- Should be done after CLI enhancement and any critical bugs
- Improves user experience by providing access to all available layouts

## Impact
- **User Experience:** Access to all 19 PowerPoint layouts in template
- **Template Completeness:** Full utilization of existing PowerPoint template
- **Content Flexibility:** More layout options for different presentation needs
- **Documentation Accuracy:** Getting_Started.md will show complete capabilities

This enhancement ensures that users can access **100% of the template capabilities** rather than the current ~68% coverage.
